kind: Service
apiVersion: v1
metadata:
  name: exchange-gateway
  labels:
    stack: payments
spec:
  selector:
    stack: payments
    app: gateway
  ports:
  - name: main
    protocol: TCP
    port: 8000
