kind: Service
apiVersion: v1
metadata:
  name: exchange-gateway
  labels:
    stack: exchange
spec:
  selector:
    stack: exchange
    app: gateway
  ports:
  - name: main
    protocol: TCP
    port: 8000
    targetPort: 8000
