apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: payments-exchange-gateway
  labels:
    stack: payments
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
      stack: payments
  replicas: 1
  template:
    metadata:
      name: payments-exchange-gateway
      labels:
        app: gateway
        stack: payments
    spec:
      imagePullSecrets:
      - name: stq
      containers:
      - name: exchange-gateway
        image: storiqateam/payments-exchange-gateway
        ports:
        - containerPort: 8000
        env:
        - name: RUN_MODE
          value: k8s
        - name: RUST_BACKTRACE
          value: "1"
        - name: RUST_LOG
          value: exchange=debug
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_URL
          value: postgresql://exgw:exgw@postgres/exgw
        volumeMounts:
        - name: conf
          mountPath: /app/config/
      volumes:
      - name: conf
        configMap:
          name: exchange-gateway
