[server]
host = "0.0.0.0"
port = 8000

[exchange_options]
test_environment = true


[limits]

  [limits.stq]
  min = 100
  max = 1000000

  [limits.btc]
  min = 0.001
  max = 1
  
  [limits.eth]
  min = 0.01
  max = 10

[graylog]
addr = "graylog-udp.internal.stq.cloud:32303"
cluster = "pay-nightly.stq.cloud"

[filelog]
path = "exchange.log"
