[server]
host = "0.0.0.0"
port = 8000

[auth]
exmo_api_key = "K-c9e22a5ca68487558a2b1d049daed37c16b25ccc"
exmo_api_secret = "S-1f1b712612c94a7ab40f76055d7a731681e2bc6f"

[client]
dns_threads = 4
exmo_url = "https://stable.stq.cloud/graphql"

[database]
url = "postgresql://exchange-gateway:exchange-gateway@exchange-gateway-pg/exchange-gateway"

[cpu_pool]
size = 1

[exchange_options]
expiration = 300 # 5 minutes
rate_upside = 0.1 # 10%
safety_threshold = 0.05 # 5%
